language: go
go:
- 1.5.1
script:
- go run *.go trending
- ls
- git clone https://github.com/constellates/dot-com.git
- ls
- mv ./*.jpg dot-com/content/assets/average_image
- ls dot-com/content/assets/average_image/
- cd dot-com
- git config --global user.name "zack"
- git config --global user.email "mail@constellates.com"
- git add content/assets/average_image/
- git commit -m "auto-image"
- git push https://$GITHUB_TOKEN@github.com/constellates/dot-com.git master
env:
  global:
  - SearchEngineId=016877701993014231384:q__vcz9b7r0
  - secure: RmUe84v474G7GripI+r6XLX7UvI3Lw2nkZcB9X3SJnJ+sZACSOlPLXQwHyaV36Y8e/F3ilEuUMCyC1r5xKb2hZWqxJLmRMlOZSNQGUmPq8K9z3j1pZHNcKpiplRjDv+duP3fUwYGYOpPom9LdnlVZZiLuzeGGld17tKXMspQ9czcIOwNRpyR7ZdZMWKiAwHMWpnLAF5RiJ3GYKzZ32WiGw+3nAf0kzzA9uYSlsDDni9+wBLwo8wT1aP0/zGD26tARiCHd+fM/DkQW/Y+GvV5fpnw5CAcG533x46XT958Ibang77YoZNXE50rpZdkaNuD3u5bIUcDiVVFaBDMEhLbVG0Hkl7yL5GzWVmtk0xq5Q5u7AhlX87XnR7TyKUPUch2GZ0DW+WqRfD5n7h+Hqi3fo7/8kFtvLsl2FijM4+hnbfkiOTJy2vcfVYN9+xYgnpgSyC3cc4UaFdEA7/xL/nD9g/weufWqPtICT730UBBELaR7YG1dkbjLulAYcKmMLHCgViKsLZ0s7H3EeSVcc9UxWPlE/ISNEq9p0/gaGpzLd8auc4OKgr+Oy7TX0S2vUDcKIEq515LVR8BDs1QkrfNemjaf2SlWN5s85nyTmLXyPMYYL3vrtPo2CTumfdMKTiYPVcesd1RDE2OZVlS22tGu6ybSTSZq2PlDxG983tKlQM=
  - secure: >-
      I1pTUsVLISsCdkG5T25L50Aw/S4gbjXCDCe40E2HI/tlauQGJ4gM9+GrjbOt+WA5gcWM8MmcHASlWhAmZzG6gPd45L8w2Z2WtMumZgtGur5SQMx4TBnhh0i0g4gpYNWQ2Ij2OD1KAFFc9m3EAD/f6Qb64yypACcEl7zwOhQXeE1QDH+eqCCoGZ9GDhsV5JzrSLxM0p6QdCQXb8VhPbyzV2b25VR8/xnhrXfjLWwtimMgKzD40d3gHmN4nlHkF2WP0u5EtJ7+z1FwX7GqmE/vGCYi47dnsJsivPD8Wd40MXLTzqxNe7cBmqR1ujPJSNcKWAUGoEzf0dB885OQjBgJHTPcmidkxpU2XqgN8lCYkhTpARi5pG5oLS0Ghhix3qQu7B+2AcpYDZm6CpIvqAWSyyWkekFTRaHEmvZIHHkLNo5wy0cz0AYf0JqJZ0wPxZily+UHTC/YFiW4aD3uULrMILwpaeKHFAKT6ObItcRWzVcH5DRIcKa0WtvkyBMTk1ITHdCEohE0BHxa7gprtygI3LmNimG+aXKFhw3i/JkRLss085KrHZb3wpMdS5tdmLghoN0e8Px5qM0UToYPcya461EWa/upfWzjzAntbK5uv975stVoMxx7eJdACo44d8k/833d4tOIF7JNOSMmPsdTuDe0W5hwwmbQjmOXgRkW4IQ=
