language: go
go:
- 1.5.1
script:
- go run *.go cat face
env:
- SearchEngineId=016877701993014231384:q__vcz9b7r0
- secure: RmUe84v474G7GripI+r6XLX7UvI3Lw2nkZcB9X3SJnJ+sZACSOlPLXQwHyaV36Y8e/F3ilEuUMCyC1r5xKb2hZWqxJLmRMlOZSNQGUmPq8K9z3j1pZHNcKpiplRjDv+duP3fUwYGYOpPom9LdnlVZZiLuzeGGld17tKXMspQ9czcIOwNRpyR7ZdZMWKiAwHMWpnLAF5RiJ3GYKzZ32WiGw+3nAf0kzzA9uYSlsDDni9+wBLwo8wT1aP0/zGD26tARiCHd+fM/DkQW/Y+GvV5fpnw5CAcG533x46XT958Ibang77YoZNXE50rpZdkaNuD3u5bIUcDiVVFaBDMEhLbVG0Hkl7yL5GzWVmtk0xq5Q5u7AhlX87XnR7TyKUPUch2GZ0DW+WqRfD5n7h+Hqi3fo7/8kFtvLsl2FijM4+hnbfkiOTJy2vcfVYN9+xYgnpgSyC3cc4UaFdEA7/xL/nD9g/weufWqPtICT730UBBELaR7YG1dkbjLulAYcKmMLHCgViKsLZ0s7H3EeSVcc9UxWPlE/ISNEq9p0/gaGpzLd8auc4OKgr+Oy7TX0S2vUDcKIEq515LVR8BDs1QkrfNemjaf2SlWN5s85nyTmLXyPMYYL3vrtPo2CTumfdMKTiYPVcesd1RDE2OZVlS22tGu6ybSTSZq2PlDxG983tKlQM=
