language: go
go:
- 1.5.1
script:
- go run *.go cat face
env:
  secure: aTjDR/Og8V6iYFv14oKGKjqa7EY0HOypQbuvpnhFc9TC7ucPEjoRTJS8X9HbfwZHgna2VCeCgnOjc6xGDCDwtse3Aw9yRvH4UK5VjXVg97Xbli8dKE0fggs3g+S8S0QaMQGwQ3nURlizdteKyYbAPhYRpb3q0ojaWmDvfvIOVwTfQiwjZqVpUTyKYZrpKnqSSyX9ueDfqEvb84cQNfT0nd8Sf1MDptVF4NHGAVPVEptuPzYVeipsK4NuzdHJl9Z53I+eKVS1d4o5NDicNcUy+VcxUSJa/9PE+ZRWxbiOOWmSrJJa0vVku5wp0eIPxYIxjMUIyUOB6PlPud4qWOhdcAzEMqjLwT11mCVrzMhYDINBRKLd4o7Mre70+xQwPW0C70JEUg7lS5w+p7JklkMvhtjLK/ULutUrNpfAsOxZunfEKNt3vTNBnjVJJZvLugksfRzaCXeUiTd3Its4pdR9+XHLzCUaMGvCUZsYAMsPUM1VrBHiCX9BO83Frvr9Q8nCIwX0vCGGuY5XTb7mAtSMZbFlR/vC2VonGqCnhGm3ZyHTjHIZsgOP2gD1q84/UKFKVinJu/zDRej/A9qE7kOaUAfiK1TBkAwfUydJe2RWbujk0JZi965two2A1BwJ3dIsB5HLaAsXUwtjOmWL2qTxr/sLfDqgOyuEiu+IhpMNBv0=
