language: go
go:
- 1.5.1
script:
- go run *.go trending
- ls
- git clone https://github.com/constellates/dot-com.git
- ls
- GENERATED_IMAGE=$(ls | grep \.jpg$)
- mv ./*.jpg dot-com/content/assets/average_image
- ls dot-com/content/assets/average_image/
- echo "![altText](/assets/average_image/$GENERATED_IMAGE)" >> dot-com/content/posts/average-image.md
- cd dot-com
- git config --global user.name "zack"
- git config --global user.email "mail@constellates.com"
- git add content/
- git commit -m "auto-image"
- git push https://$GITHUB_TOKEN@github.com/constellates/dot-com.git master
env:
  global:
  - SearchEngineId=016877701993014231384:q__vcz9b7r0
  - secure: RmUe84v474G7GripI+r6XLX7UvI3Lw2nkZcB9X3SJnJ+sZACSOlPLXQwHyaV36Y8e/F3ilEuUMCyC1r5xKb2hZWqxJLmRMlOZSNQGUmPq8K9z3j1pZHNcKpiplRjDv+duP3fUwYGYOpPom9LdnlVZZiLuzeGGld17tKXMspQ9czcIOwNRpyR7ZdZMWKiAwHMWpnLAF5RiJ3GYKzZ32WiGw+3nAf0kzzA9uYSlsDDni9+wBLwo8wT1aP0/zGD26tARiCHd+fM/DkQW/Y+GvV5fpnw5CAcG533x46XT958Ibang77YoZNXE50rpZdkaNuD3u5bIUcDiVVFaBDMEhLbVG0Hkl7yL5GzWVmtk0xq5Q5u7AhlX87XnR7TyKUPUch2GZ0DW+WqRfD5n7h+Hqi3fo7/8kFtvLsl2FijM4+hnbfkiOTJy2vcfVYN9+xYgnpgSyC3cc4UaFdEA7/xL/nD9g/weufWqPtICT730UBBELaR7YG1dkbjLulAYcKmMLHCgViKsLZ0s7H3EeSVcc9UxWPlE/ISNEq9p0/gaGpzLd8auc4OKgr+Oy7TX0S2vUDcKIEq515LVR8BDs1QkrfNemjaf2SlWN5s85nyTmLXyPMYYL3vrtPo2CTumfdMKTiYPVcesd1RDE2OZVlS22tGu6ybSTSZq2PlDxG983tKlQM=
  - secure: SKSKr8Y5MDF6NZoFqy2Sx2i8yDE+4WMvA4FLVTNOlh664zB0IalDhqRUoZOpFet3RRs04qGcUaempJ3rMBVqBG2OU6mDzYvPgHWPad6eSg2qNt3KuKSiXHSnY9Syq589YOWNk3iICyug29f7lU3i7G0bVVnQ3AMhWUjH2iUwnh8etGZ1xUB/vsWg1jFNwzP3Zdqt8jn3wI3v+Y8G/eOOsH93mcvKCnJXYuQ0mMNUWKusP/8bgtgFGC0386w9dIvtRFQYYxXiAa8aMEDJfFs/8mTNY+8Du5ERS4/K5iR2JCD4M+ulbcncA/tg9Bv4umWwCxHTWbjBYsot3WBZYlX06btnvCmU4D055hTusXLkheovw8ycejAXLCjPv0o/tbP8iYZOUzOTYJ+VbCr+aYSRKZ0Y780wsxS2c7XX3MVrNlPoiiQYM10EOVOojJVzfiYagAehTU8WBe3Zme2ztBYQATH+NVKmMzN9SLM5Efh51T67rO+qV+3FmDOFg0ORS9//YdRVEnfvJW6SVdALQXofCz8a+dseI4EWGxFVCU8lVFVyQzGNDmy7L1yTU8IRhuWNxdFLWi44dA8hsv7MBJTbc1wUIubgVuJe8+xog9hUpCZTcQxpV+iGJzhoQMAmImREi5WBscK45xv/jpuUQCI5SZ1pNeMSB9866YXp+AWbgKM=
